### ISSUE TITLE
dpkg-buildpackage的时候报“没有秘匙”，请问怎么解决

### ISSUE THREAD

**Issue by CokinLee** [yyk123/XwareDesktop#5]
signfile xware-desktop_0.13.20180825.dsc
gpg: “yangyk <1520972296@qq.com>”已跳过：没有秘匙
gpg: dpkg-sign.T9sCICeZ/xware-desktop_0.13.20180825.dsc: clear-sign failed: 没有秘匙

**Comment by TuvokYang** [comment]
忽略即可
